# Generated by Django 5.2.3 on 2025-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Organization', 'Organization'), ('Campus-cheif', 'Campus-cheif'), ('Admin', 'Admin')], default='student', max_length=20),
        ),
    ]
