# Generated by Django 5.2.3 on 2025-08-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, choices=[('csit_union', 'Union of CSIT Students'), ('it_alliance', 'Information Technology Alliance'), ('physics_society', 'Physics Society'), ('biology_club', 'Biology Club'), ('chemistry_assoc', 'Chemistry Association'), ('food_tech_forum', 'Food Technology Forum'), ('nutrition_group', 'Nutrition and Dietetics Group')], max_length=50, null=True),
        ),
    ]
