# Generated by Django 5.2.3 on 2025-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_class_name_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(choices=[('BSc.CSIT', 'BSc.CSIT'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MSc.CSIT', 'MSc.CSIT'), ('BSc.IT', 'BSc.IT'), ('BSc.Micro', 'BSc.Micro'), ('BSc.BioTech', 'BSc.BioTech'), ('MSc.IT', 'MSc.IT'), ('MBA', 'MBA'), ('BPharma', 'BPharma')], default='BSc.CSIT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1 Semester'), ('2', '2 Semester'), ('3', '3 Semester'), ('4', '4 Semester'), ('5', '5 Semester'), ('6', '6 Semester'), ('7', '7 Semester'), ('8', '8 Semester')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1 Year'), ('2', '2 Year'), ('3', '3 Year'), ('4', '4 Year')], max_length=2, null=True),
        ),
    ]
