# Generated by Django 5.2.3 on 2025-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_class_name_alter_profile_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Department', 'Department'), ('Organization', 'Organization'), ('Campus-cheif', 'Campus-cheif'), ('Admin', 'Admin')], default='student', max_length=20),
        ),
    ]
