# Generated by Django 5.2.3 on 2025-08-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(blank=True, choices=[('BSc.CSIT', 'BSc.CSIT'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('MSc.CSIT', 'MSc.CSIT'), ('BSc.IT', 'BSc.IT'), ('BSc.Micro', 'BSc.Micro'), ('BSc.BioTech', 'BSc.BioTech'), ('MSc.IT', 'MSc.IT'), ('MBA', 'MBA'), ('BPharma', 'BPharma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Department', 'Department'), ('Organization', 'Organization'), ('Campus-cheif', 'Campus-cheif'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
