# Generated by Django 5.2.3 on 2025-08-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remindersent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_created', 'Event Created'), ('event_approved', 'Event Approved'), ('event_rejected', 'Event Rejected'), ('event_cancelled', 'Event Cancelled'), ('registration_confirmation', 'Registration Confirmation'), ('event_update', 'Event Update'), ('event_completed', 'Event Completed'), ('reminder', 'Reminder'), ('general', 'General')], max_length=50),
        ),
    ]
