# Generated by Django 5.2.3 on 2025-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_level',
            field=models.CharField(choices=[('class', 'Class Level'), ('faculty', 'Faculty_Level'), ('department', 'Department_Level'), ('college', 'College_Level')], max_length=20),
        ),
    ]
