# Generated by Django 5.2.3 on 2025-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code_data',
            field=models.CharField(blank=True, help_text='Unique QR code string for attendance verification', max_length=50, null=True),
        ),
    ]
