# Generated by Django 5.2.3 on 2025-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_qr_code_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completion_notified',
            field=models.BooleanField(default=False),
        ),
    ]
