# Generated by Django 5.2.3 on 2025-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_completion_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_level',
            field=models.CharField(choices=[('class', 'Class Level'), ('department', 'Department_Level'), ('organization', 'Organization_Level'), ('college', 'College_Level')], max_length=20),
        ),
    ]
