# Generated by Django 5.2.3 on 2025-08-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_class_name_event_semester_event_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='semester',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
